# -*- coding: utf-8 -*-
# Part of Odoo. See LICENSE file for full copyright and licensing details.

{
    'name': "Hospital Management",
    'category': 'Hospital',
    'version': '1.0.0',
    'sequence': -10,
    'author': 'Ali Mohamed Mahmoud',
    'summary': "Hospital Management system",
    'description': "Hospital Management system",
    'depends': ['mail', 'product'],
    'data': [
        'security/ir.model.access.csv',
        'data/patient_tag_data.xml',
        'data/patient.tag.csv',
        'data/mail_template_data.xml',
        'wizard/cancel_appointment_view.xml',
        'views/menu.xml',
        'views/patient_view.xml',
        'views/sequence_data.xml',
        'views/patient_tag_view.xml',
        'views/female_patient_view.xml',
        'views/odoo_playground.xml',
        'views/appointment_view.xml',
        'views/res_config_settings_views.xml',
        'views/operation.xml',
        'reports/report.xml',
        'reports/patient_card.xml',
        'reports/sale_report_inherit.xml',
        'reports/appointment_details.xml',],
    'demo': [],
    'application': True,
    'auto_install': False,
    'license': 'LGPL-3',
}
